services:
  mysql:
    image: mysql:8.0
    container_name: mysql-sakila
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: sakila
    ports:
      - "3307:3306" # PortWindows: PortContainer
    volumes:
      - ./mysql_sakila_data:/var/lib/mysql
